# -*- coding: utf-8 -*-
"""PCOS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_CfUv4L7Vpd4K5Us-IiNWXXQ9darS2Vi
"""

!pip install tensorflow scikit-learn pillow

from google.colab import drive
drive.mount('/content/drive')

import os, random
import numpy as np
import tensorflow as tf
from PIL import Image
from sklearn.utils.class_weight import compute_class_weight

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras import layers, Model
from tensorflow.keras import mixed_precision

# ⚡ Faster + better training
mixed_precision.set_global_policy('mixed_float16')

# Paths
BASE_PATH = '/content/drive/MyDrive/PCOS/PCOS'
SAVE_DIR  = '/content/drive/MyDrive/PCOS/saved_models_1/'
os.makedirs(SAVE_DIR, exist_ok=True)

IMG_SIZE   = (224, 224)
BATCH_SIZE = 16   # smaller = better generalization
EPOCHS     = 30

VALID_EXT = {'.jpg','.jpeg','.png','.bmp','.tiff','.tif','.webp'}

bad_files, other_files = [], []

for root, _, files in os.walk(BASE_PATH):
    for f in files:
        path = os.path.join(root, f)
        ext  = os.path.splitext(f)[1].lower()

        if ext not in VALID_EXT:
            other_files.append(path)
            continue

        try:
            img = Image.open(path)
            img.verify()
        except:
            bad_files.append(path)

for f in bad_files + other_files:
    os.remove(f)

print(f"Removed {len(bad_files)} corrupt & {len(other_files)} non-image files")

class SafeImageDataset:
    def __init__(self, base_path, img_size, batch_size,
                 augment=False, val_split=0.2, subset='training', seed=42):

        self.img_size   = img_size
        self.batch_size = batch_size
        self.augment    = augment

        samples = []
        self.class_indices = {}

        classes = sorted([d for d in os.listdir(base_path)
                          if os.path.isdir(os.path.join(base_path, d))])

        print("Classes:", classes)

        for idx, cls in enumerate(classes):
            self.class_indices[cls] = idx
            for f in os.listdir(os.path.join(base_path, cls)):
                path = os.path.join(base_path, cls, f)
                samples.append((path, idx))

        random.seed(seed)
        random.shuffle(samples)

        split = int(len(samples) * (1 - val_split))
        self.samples = samples[:split] if subset=='training' else samples[split:]

        self.num_classes = len(classes)

    def augment_fn(self, img):
        img = tf.image.random_flip_left_right(img)
        img = tf.image.random_flip_up_down(img)

        img = tf.image.random_brightness(img, 0.2)
        img = tf.image.random_contrast(img, 0.7, 1.3)
        img = tf.image.random_saturation(img, 0.7, 1.3)

        img = tf.image.random_crop(img, [200,200,3])
        img = tf.image.resize(img, self.img_size)
        return img

    def get_tf_dataset(self):
        paths  = [s[0] for s in self.samples]
        labels = [s[1] for s in self.samples]

        def load(path, label):
            img = tf.io.read_file(path)
            img = tf.image.decode_image(img, channels=3)
            img = tf.image.resize(img, self.img_size)
            img = tf.cast(img, tf.float32)/255.0

            if self.augment:
                img = self.augment_fn(img)

            label = tf.one_hot(label, self.num_classes)
            return img, label

        ds = tf.data.Dataset.from_tensor_slices((paths, labels))
        ds = ds.map(load, num_parallel_calls=tf.data.AUTOTUNE)
        ds = ds.batch(self.batch_size).prefetch(tf.data.AUTOTUNE)
        return ds, labels

class SafeImageDataset:
    def __init__(self, base_path, img_size, batch_size,
                 augment=False, val_split=0.2, subset='training', seed=42):

        self.img_size   = img_size
        self.batch_size = batch_size
        self.augment    = augment

        samples = []
        self.class_indices = {}

        classes = sorted([
            d for d in os.listdir(base_path)
            if os.path.isdir(os.path.join(base_path, d))
        ])

        print("Classes:", classes)

        for idx, cls in enumerate(classes):
            self.class_indices[cls] = idx
            cls_path = os.path.join(base_path, cls)

            for f in os.listdir(cls_path):
                path = os.path.join(cls_path, f)
                samples.append((path, idx))

        random.seed(seed)
        random.shuffle(samples)

        split = int(len(samples) * (1 - val_split))
        self.samples = samples[:split] if subset=='training' else samples[split:]

        self.num_classes = len(classes)

    # 🔥 Improved augmentation
    def augment_fn(self, img):
        img = tf.image.random_flip_left_right(img)
        img = tf.image.random_flip_up_down(img)

        img = tf.image.random_brightness(img, 0.2)
        img = tf.image.random_contrast(img, 0.7, 1.3)
        img = tf.image.random_saturation(img, 0.7, 1.3)

        img = tf.image.random_crop(img, [200, 200, 3])
        img = tf.image.resize(img, self.img_size)

        return img

    # ✅ FIXED loader (this solves your error)
    def get_tf_dataset(self):
        paths  = [s[0] for s in self.samples]
        labels = [s[1] for s in self.samples]

        def load(path, label):
            img = tf.io.read_file(path)

            # 🔥 decode safely (all formats)
            img = tf.image.decode_image(img, channels=3, expand_animations=False)

            # 🔥 CRITICAL FIX (prevents your error)
            img.set_shape([None, None, 3])

            img = tf.image.resize(img, self.img_size)
            img = tf.cast(img, tf.float32) / 255.0

            if self.augment:
                img = self.augment_fn(img)

            label = tf.one_hot(label, self.num_classes)
            return img, label

        ds = tf.data.Dataset.from_tensor_slices((paths, labels))
        ds = ds.map(load, num_parallel_calls=tf.data.AUTOTUNE)
        ds = ds.batch(self.batch_size).prefetch(tf.data.AUTOTUNE)

        return ds, labels

# ─── Load datasets ───
train_obj = SafeImageDataset(
    BASE_PATH, IMG_SIZE, BATCH_SIZE,
    augment=True, subset='training'
)

val_obj = SafeImageDataset(
    BASE_PATH, IMG_SIZE, BATCH_SIZE,
    augment=False, subset='validation'
)

train_ds, train_labels = train_obj.get_tf_dataset()
val_ds, _              = val_obj.get_tf_dataset()

NUM_CLASSES = train_obj.num_classes

print("\nClass mapping:", train_obj.class_indices)
print("Total classes:", NUM_CLASSES)


# ─── Compute class weights (IMPORTANT) ───
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

train_labels_np = np.array(train_labels)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_labels_np),
    y=train_labels_np
)

class_weights = dict(enumerate(class_weights))

print("\nClass weights:", class_weights)

def build_model(num_classes):
    base = EfficientNetB0(include_top=False,
                          weights='imagenet',
                          input_shape=(*IMG_SIZE,3))
    base.trainable = False

    inputs = tf.keras.Input(shape=(*IMG_SIZE,3))
    x = base(inputs, training=False)
    x = layers.GlobalAveragePooling2D()(x)

    x = layers.BatchNormalization()(x)
    x = layers.Dense(256, activation='relu',
                     kernel_regularizer=tf.keras.regularizers.l2(0.01))(x)
    x = layers.Dropout(0.5)(x)

    x = layers.Dense(128, activation='relu',
                     kernel_regularizer=tf.keras.regularizers.l2(0.01))(x)
    x = layers.Dropout(0.4)(x)

    outputs = layers.Dense(num_classes, activation='softmax')(x)

    return Model(inputs, outputs)

model = build_model(NUM_CLASSES)

model.compile(
    optimizer=tf.keras.optimizers.Adam(3e-4),
    loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.1),
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc', multi_label=True)]
)

model.summary()

callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_loss', patience=5, restore_best_weights=True
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        factor=0.3, patience=2, min_lr=1e-6
    ),
    tf.keras.callbacks.ModelCheckpoint(
        SAVE_DIR + 'best.keras',
        monitor='val_auc',
        save_best_only=True,
        mode='max'
    )
]

history1 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    callbacks=callbacks,
    class_weight=class_weights
)

model.layers[1].trainable = True

for layer in model.layers[1].layers[:-100]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),
    loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.1),
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc', multi_label=True)]
)

history2 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    callbacks=callbacks,
    class_weight=class_weights
)

model.save(SAVE_DIR + 'final_model.keras')
print("Model saved successfully!")

import tensorflow as tf

model = tf.keras.models.load_model("/content/drive/MyDrive/PCOS/saved_models_1/final_model.keras")

model.save_weights("weights.h5")

model.save("fixed_model.h5")

model.save("fixed_model.h5", include_optimizer=False)

import tensorflow as tf

model = tf.keras.models.load_model("/content/drive/MyDrive/PCOS/saved_models_1/final_model.keras")

# SAVE AS TENSORFLOW SAVEDMODEL (FOLDER)
model.export("fixed_model_tf")

model.export("/content/drive/MyDrive/PCOS/saved_models_final/fixed_model_tf")

model.save("fixed_model.keras")

import tensorflow as tf

print(tf.__version__)  # IMPORTANT

# Load your original model (whatever you used before)
model = tf.keras.models.load_model("/content/drive/MyDrive/PCOS/saved_models_1/final_model.keras", compile=False)

# Re-save properly in stable format
model.save("final_model.h5")

import tensorflow as tf

# load your current model (the one giving error)
model = tf.keras.models.load_model("/content/drive/MyDrive/PCOS/saved_models_1/final_model.keras", compile=False)

# 🔥 rebuild clean model (THIS FIXES config issues)
new_model = tf.keras.Sequential.from_config(model.get_config())

# copy weights
new_model.set_weights(model.get_weights())

# save in stable format
new_model.save("clean_model.h5")

model.save_weights("weights.weights.h5")