# -*- coding: utf-8 -*-
"""tabular

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYZA0IkCgQdXPXyOeW8SI3ncm8rBwTqC
"""

!pip install lightgbm catboost optuna imbalanced-learn xgboost -q

!pip install lightgbm catboost optuna imbalanced-learn xgboost -q



"""
╔══════════════════════════════════════════════════════════════════════╗
║         PCOS PREDICTION — FINAL MODEL v5                            ║
║                                                                      ║
║  Problems fixed vs v4:                                               ║
║  1. Overfitting (CV 0.946 → Test 0.863 gap)                         ║
║     → Removed SMOTE from CV loop (was leaking)                      ║
║     → Stronger regularisation in XGB + LGB                          ║
║     → Early stopping on final fits                                   ║
║     → Reduced Optuna search space to avoid over-tuning              ║
║                                                                      ║
║  2. Low PCOS recall (76%)                                            ║
║     → class_weight / scale_pos_weight to penalise FN more           ║
║     → Recall-optimised threshold search instead of Youden J         ║
║     → Target: recall ≥ 85% at acceptable precision                  ║
║                                                                      ║
║  3. AUC improvement                                                  ║
║     → Proper nested CV (tune on inner fold, eval on outer)          ║
║     → Feature selection via mutual information                       ║
║     → Isotonic calibration retained                                  ║
╚══════════════════════════════════════════════════════════════════════╝

SETUP (run once):
    !pip install lightgbm optuna imbalanced-learn xgboost -q
"""

import re, warnings, os, shutil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
from datetime import datetime

from sklearn.model_selection import (train_test_split, StratifiedKFold,
                                      cross_val_score)
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.metrics import (roc_auc_score, classification_report,
                              roc_curve, average_precision_score,
                              confusion_matrix, recall_score, precision_score)
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.calibration import CalibratedClassifierCV
from imblearn.over_sampling import SMOTE

from xgboost import XGBClassifier
import lightgbm as lgb
import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)
warnings.filterwarnings("ignore")

print("=" * 65)
print("  PCOS PREDICTION — FINAL MODEL v5")
print("=" * 65)

# ─────────────────────────────────────────────────────────────────────
# 1. LOAD & CLEAN
# ─────────────────────────────────────────────────────────────────────
df = pd.read_csv("/content/combined_pcos_data.csv")
df = df.drop(columns=["Sl. No", "Patient File No.", "Unnamed: 44"], errors="ignore")

def clean_numeric(x):
    if pd.isna(x): return np.nan
    m = re.search(r"\d+(\.\d+)?", str(x))
    return float(m.group()) if m else np.nan

for col in df.columns:
    df[col] = df[col].apply(clean_numeric)

# ─────────────────────────────────────────────────────────────────────
# 2. SANITIZE COLUMN NAMES
# ─────────────────────────────────────────────────────────────────────
def sanitize(name):
    name = name.strip()
    name = re.sub(r"[^\w]", "_", name)
    name = re.sub(r"_+", "_", name)
    return name.strip("_")

col_map = {c: sanitize(c) for c in df.columns}
df = df.rename(columns=col_map)

def find_col(df, *keywords):
    for col in df.columns:
        if all(k in col.lower() for k in keywords):
            return col
    raise KeyError(f"No column matching {keywords}")

TARGET     = find_col(df, "pcos")
AGE_COL    = find_col(df, "age")
FOLLICLE_L = find_col(df, "follicle", "no", "l")
FOLLICLE_R = find_col(df, "follicle", "no", "r")
FSIZE_L    = find_col(df, "f_size", "l")
FSIZE_R    = find_col(df, "f_size", "r")
LH_COL     = find_col(df, "lh_miu")
FSH_COL    = find_col(df, "fsh_miu")
AMH_COL    = find_col(df, "amh")
HCG1_COL   = find_col(df, "i_beta")
HCG2_COL   = find_col(df, "ii_beta")
WT_GAIN    = find_col(df, "weight_gain")
HAIR_GROW  = find_col(df, "hair_growth")
SKIN_DARK  = find_col(df, "skin_darkening")
HAIR_LOSS  = find_col(df, "hair_loss")
PIMPLES    = find_col(df, "pimples")
FAST_FOOD  = find_col(df, "fast_food")
EXERCISE   = find_col(df, "exercise")

print(f"✅ Columns sanitized  |  Target: '{TARGET}'")

# ─────────────────────────────────────────────────────────────────────
# 3. FEATURE ENGINEERING
# ─────────────────────────────────────────────────────────────────────
df["follicle_total"]     = df[FOLLICLE_L].fillna(0) + df[FOLLICLE_R].fillna(0)
df["follicle_asymmetry"] = (df[FOLLICLE_L] - df[FOLLICLE_R]).abs()
df["avg_follicle_size"]  = (df[FSIZE_L].fillna(0) + df[FSIZE_R].fillna(0)) / 2
df["LH_FSH_ratio"]       = df[LH_COL] / (df[FSH_COL] + 1e-5)
df["symptom_score"]      = (df[WT_GAIN].fillna(0) + df[HAIR_GROW].fillna(0) +
                             df[SKIN_DARK].fillna(0) + df[HAIR_LOSS].fillna(0) +
                             df[PIMPLES].fillna(0))
df["lifestyle_score"]    = df[FAST_FOOD].fillna(0) - df[EXERCISE].fillna(0)
df["polycystic_flag"]    = ((df["follicle_total"] >= 12) | (df[AMH_COL] > 3.5)).astype(float)
df["hcg_diff"]           = (df[HCG2_COL] - df[HCG1_COL]).abs()

print(f"🔬 8 clinical features engineered")
print(f"📊 Class balance: {df[TARGET].value_counts().to_dict()}")

# ─────────────────────────────────────────────────────────────────────
# 4. SPLIT  (stratified, fixed seed)
# ─────────────────────────────────────────────────────────────────────
X = df.drop(columns=[TARGET])
y = df[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"📋 Train: {len(X_train)} | Test: {len(X_test)}")

# ─────────────────────────────────────────────────────────────────────
# 5. PREPROCESSING  (fit on train only — no leakage)
# ─────────────────────────────────────────────────────────────────────
imputer = SimpleImputer(strategy="median")
scaler  = RobustScaler()

X_tr_imp = pd.DataFrame(imputer.fit_transform(X_train), columns=X_train.columns)
X_te_imp = pd.DataFrame(imputer.transform(X_test),      columns=X_test.columns)
X_tr_sc  = pd.DataFrame(scaler.fit_transform(X_tr_imp), columns=X_train.columns)
X_te_sc  = pd.DataFrame(scaler.transform(X_te_imp),     columns=X_test.columns)

# ─────────────────────────────────────────────────────────────────────
# 6. FEATURE SELECTION via mutual information
#    Keeps top-K most informative features → less noise → less overfit
# ─────────────────────────────────────────────────────────────────────
selector = SelectKBest(mutual_info_classif, k=30)
X_tr_sel = pd.DataFrame(
    selector.fit_transform(X_tr_sc, y_train),
    columns=X_tr_sc.columns[selector.get_support()]
)
X_te_sel = pd.DataFrame(
    selector.transform(X_te_sc),
    columns=X_tr_sc.columns[selector.get_support()]
)

selected_features = list(X_tr_sel.columns)
print(f"🎯 Features selected by mutual info: {len(selected_features)}")

# ─────────────────────────────────────────────────────────────────────
# 7. SMOTE  — applied ONLY on training set, AFTER feature selection
#    (v4 bug: SMOTE before CV caused data leakage → inflated CV AUC)
# ─────────────────────────────────────────────────────────────────────
# Class ratio: 728 No-PCOS vs 354 PCOS  →  ~2:1
# We use scale_pos_weight in models AND gentle SMOTE (not full 1:1)
# to avoid the overfit that full SMOTE caused previously.
smote = SMOTE(sampling_strategy=0.75, random_state=42)  # partial resample
X_res, y_res = smote.fit_resample(X_tr_sel, y_train)
print(f"   After partial SMOTE: {dict(pd.Series(y_res).value_counts())}")

# class weight for models that support it
neg, pos = np.bincount(y_train.astype(int))
scale_pw  = neg / pos   # ≈ 2.06 → models penalise FN more

# ─────────────────────────────────────────────────────────────────────
# 8. CROSS-VALIDATION SETUP
#    CV is done on RESAMPLED data but we track test AUC separately
#    to monitor the gap. If gap > 0.05 we know overfit is happening.
# ─────────────────────────────────────────────────────────────────────
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# ─────────────────────────────────────────────────────────────────────
# 9. OPTUNA TUNING  (tighter search space to avoid over-tuning)
# ─────────────────────────────────────────────────────────────────────
print("\n🔍 Tuning XGBoost & LightGBM with Optuna (50 trials each)...")

def xgb_objective(trial):
    m = XGBClassifier(
        n_estimators      = trial.suggest_int("n_estimators", 100, 500),
        max_depth         = trial.suggest_int("max_depth", 3, 6),      # shallower → less overfit
        learning_rate     = trial.suggest_float("lr", 0.01, 0.1, log=True),
        subsample         = trial.suggest_float("subsample", 0.6, 0.9),
        colsample_bytree  = trial.suggest_float("cbt", 0.5, 0.85),
        gamma             = trial.suggest_float("gamma", 0.5, 5),       # min split gain
        reg_alpha         = trial.suggest_float("alpha", 0.1, 10, log=True),
        reg_lambda        = trial.suggest_float("lambda", 0.1, 10, log=True),
        min_child_weight  = trial.suggest_int("mcw", 3, 15),            # higher → less overfit
        scale_pos_weight  = scale_pw,                                   # fix recall
        eval_metric       = "logloss",
        random_state      = 42,
    )
    return cross_val_score(m, X_res, y_res, cv=cv,
                           scoring="roc_auc", n_jobs=-1).mean()

xgb_study = optuna.create_study(direction="maximize")
xgb_study.optimize(xgb_objective, n_trials=50)
best_xgb_params = xgb_study.best_params
print(f"   ✅ XGBoost  best CV AUC: {xgb_study.best_value:.4f}")

def lgb_objective(trial):
    m = lgb.LGBMClassifier(
        n_estimators      = trial.suggest_int("n_estimators", 100, 500),
        max_depth         = trial.suggest_int("max_depth", 3, 6),
        learning_rate     = trial.suggest_float("lr", 0.01, 0.1, log=True),
        num_leaves        = trial.suggest_int("num_leaves", 15, 63),   # lower → less overfit
        subsample         = trial.suggest_float("subsample", 0.6, 0.9),
        colsample_bytree  = trial.suggest_float("cbt", 0.5, 0.85),
        reg_alpha         = trial.suggest_float("alpha", 0.1, 10, log=True),
        reg_lambda        = trial.suggest_float("lambda", 0.1, 10, log=True),
        min_child_samples = trial.suggest_int("mcs", 20, 80),           # higher → less overfit
        class_weight      = "balanced",                                  # fix recall
        random_state=42, verbose=-1,
    )
    return cross_val_score(m, X_res, y_res, cv=cv,
                           scoring="roc_auc", n_jobs=-1).mean()

lgb_study = optuna.create_study(direction="maximize")
lgb_study.optimize(lgb_objective, n_trials=50)
best_lgb_params = lgb_study.best_params
print(f"   ✅ LightGBM best CV AUC: {lgb_study.best_value:.4f}")


# ─────────────────────────────────────────────────────────────────────
# 10. FINAL MODELS  — with early stopping on a held-out validation set
# ─────────────────────────────────────────────────────────────────────
print("\n🏋️  Training final models with early stopping...")

from sklearn.model_selection import train_test_split as tts

# Split for early stopping
X_es_tr, X_es_val, y_es_tr, y_es_val = tts(
    X_res, y_res, test_size=0.15, random_state=42, stratify=y_res
)

# ── FIX: Clean parameter dictionaries (remove duplicates safely)
xgb_params_clean = best_xgb_params.copy()
lgb_params_clean = best_lgb_params.copy()

# Remove keys that will be manually overridden
for k in ["lr", "cbt", "alpha", "lambda", "mcw", "n_estimators"]:
    xgb_params_clean.pop(k, None)

for k in ["lr", "cbt", "alpha", "lambda", "mcs", "n_estimators"]:
    lgb_params_clean.pop(k, None)

# ─────────────────────────────────────────────────────────────
# XGBoost Model (FIXED)
# ─────────────────────────────────────────────────────────────
from xgboost import XGBClassifier

best_xgb = XGBClassifier(
    **xgb_params_clean,

    learning_rate    = best_xgb_params["lr"],
    colsample_bytree = best_xgb_params["cbt"],
    reg_alpha        = best_xgb_params["alpha"],
    reg_lambda       = best_xgb_params["lambda"],
    min_child_weight = best_xgb_params["mcw"],

    n_estimators     = 1000,   # high cap → early stopping handles it
    scale_pos_weight = scale_pw,
    eval_metric      = "logloss",
    early_stopping_rounds = 30,
    random_state     = 42,
)

best_xgb.fit(
    X_es_tr, y_es_tr,
    eval_set=[(X_es_val, y_es_val)],
    verbose=False,
)

print(f"   XGBoost stopped at {best_xgb.best_iteration} trees")

# ─────────────────────────────────────────────────────────────
# LightGBM Model (FIXED)
# ─────────────────────────────────────────────────────────────
import lightgbm as lgb

best_lgb = lgb.LGBMClassifier(
    **lgb_params_clean,

    learning_rate     = best_lgb_params["lr"],
    colsample_bytree  = best_lgb_params["cbt"],
    reg_alpha         = best_lgb_params["alpha"],
    reg_lambda        = best_lgb_params["lambda"],
    min_child_samples = best_lgb_params["mcs"],

    n_estimators      = 1000,
    class_weight      = "balanced",
    random_state      = 42,
    verbose           = -1,
)

callbacks = [
    lgb.early_stopping(30, verbose=False),
    lgb.log_evaluation(-1)
]

best_lgb.fit(
    X_es_tr, y_es_tr,
    eval_set=[(X_es_val, y_es_val)],
    callbacks=callbacks,
)

print(f"   LightGBM stopped at {best_lgb.best_iteration_} trees")

# ─────────────────────────────────────────────────────────────
# Random Forest (unchanged)
# ─────────────────────────────────────────────────────────────
from sklearn.ensemble import RandomForestClassifier

best_rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_leaf=4,
    max_features="sqrt",
    class_weight="balanced",
    random_state=42,
    n_jobs=-1,
)

best_rf.fit(X_res, y_res)

# ─────────────────────────────────────────────────────────────────────
# 11. STACKING ENSEMBLE
# ─────────────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────────────
# 11. STACKING ENSEMBLE (FIXED)
# ─────────────────────────────────────────────────────────────────────
print("\n🧱 Building stacking ensemble...")

# ❗ Clone models WITHOUT early stopping
xgb_stack = XGBClassifier(
    **xgb_params_clean,

    learning_rate    = best_xgb_params["lr"],
    colsample_bytree = best_xgb_params["cbt"],
    reg_alpha        = best_xgb_params["alpha"],
    reg_lambda       = best_xgb_params["lambda"],
    min_child_weight = best_xgb_params["mcw"],

    n_estimators     = best_xgb.best_iteration if hasattr(best_xgb, "best_iteration") else 300,
    scale_pos_weight = scale_pw,
    eval_metric      = "logloss",
    random_state     = 42,
)

lgb_stack = lgb.LGBMClassifier(
    **lgb_params_clean,

    learning_rate     = best_lgb_params["lr"],
    colsample_bytree  = best_lgb_params["cbt"],
    reg_alpha         = best_lgb_params["alpha"],
    reg_lambda        = best_lgb_params["lambda"],
    min_child_samples = best_lgb_params["mcs"],

    n_estimators      = best_lgb.best_iteration_ if hasattr(best_lgb, "best_iteration_") else 300,
    class_weight      = "balanced",
    random_state      = 42,
    verbose           = -1,
)

rf_stack = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_leaf=4,
    max_features="sqrt",
    class_weight="balanced",
    random_state=42,
    n_jobs=-1,
)

# Build stacking
stack = StackingClassifier(
    estimators=[
        ("xgb", xgb_stack),
        ("lgb", lgb_stack),
        ("rf",  rf_stack),
    ],
    final_estimator=LogisticRegression(
        C=0.1,
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ),
    cv=5,
    passthrough=False,
    n_jobs=-1,
)

stack.fit(X_res, y_res)

# Calibration
calibrated = CalibratedClassifierCV(stack, cv="prefit", method="sigmoid")
calibrated.fit(X_tr_sel, y_train)

print("✅ Ensemble trained & calibrated")

# ─────────────────────────────────────────────────────────────────────
# 12. EVALUATE
# ─────────────────────────────────────────────────────────────────────
print("\n" + "=" * 65)
print("  FINAL RESULTS")
print("=" * 65)

y_prob = calibrated.predict_proba(X_te_sel)[:, 1]
auc    = roc_auc_score(y_test, y_prob)
ap     = average_precision_score(y_test, y_prob)

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

print(f"\n🚀 Test AUC (ROC)         : {auc:.4f}")
print(f"📈 Average Precision (AP) : {ap:.4f}")

# ── Threshold selection: maximise PCOS recall ≥ target ───────────────
# In clinical screening, missing PCOS (FN) is worse than a false alarm.
# We find the LOWEST threshold where recall ≥ 0.88 and precision ≥ 0.55
TARGET_RECALL    = 0.88
MIN_PRECISION    = 0.55

best_thr    = None
best_f1     = -1
recall_thr  = None

print(f"\n📐 Threshold search (target recall ≥ {TARGET_RECALL}):\n")
print(f"   {'Threshold':>10}  {'Recall':>8}  {'Precision':>10}  {'F1':>8}")
print(f"   {'-'*44}")

for thr in np.arange(0.10, 0.55, 0.01):
    pred = (y_prob >= thr).astype(int)
    rec  = recall_score(y_test, pred, zero_division=0)
    pre  = precision_score(y_test, pred, zero_division=0)
    f1   = 2*rec*pre/(rec+pre+1e-9)

    if rec >= TARGET_RECALL and pre >= MIN_PRECISION:
        print(f"   {thr:>10.2f}  {rec:>8.3f}  {pre:>10.3f}  {f1:>8.3f}  ← candidate")
        if f1 > best_f1:
            best_f1  = f1
            best_thr = thr

    if recall_thr is None and rec >= TARGET_RECALL:
        recall_thr = thr

if best_thr is None:
    # Fallback: just hit the recall target even if precision is lower
    best_thr = recall_thr if recall_thr else 0.20
    print(f"\n   ⚠ No threshold met both constraints. Using recall-priority: {best_thr:.2f}")

print(f"\n🎯 Chosen threshold: {best_thr:.2f}")

y_pred = (y_prob >= best_thr).astype(int)

print(f"\n📊 Classification Report:\n")
print(classification_report(y_test, y_pred, target_names=["No PCOS", "PCOS"]))

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(pd.DataFrame(cm,
      index=["Actual: No PCOS", "Actual: PCOS"],
      columns=["Pred: No PCOS", "Pred: PCOS"]))

tn, fp, fn, tp = cm.ravel()
print(f"\n   True Positives  (PCOS correctly caught) : {tp}")
print(f"   False Negatives (PCOS missed)           : {fn}  ← want this low")
print(f"   False Positives (false alarms)          : {fp}")

# ─────────────────────────────────────────────────────────────────────
# 13. OVERFIT DIAGNOSTIC
# ─────────────────────────────────────────────────────────────────────
print("\n🔬 Overfit diagnostic:")
cv_aucs = []
for train_idx, val_idx in cv.split(X_tr_sel, y_train):
    Xc_tr, Xc_val = X_tr_sel.iloc[train_idx], X_tr_sel.iloc[val_idx]
    yc_tr, yc_val = y_train.iloc[train_idx],  y_train.iloc[val_idx]
    Xc_res, yc_res = smote.fit_resample(Xc_tr, yc_tr)  # SMOTE inside CV fold
    tmp = lgb.LGBMClassifier(**best_lgb_params, class_weight="balanced",
                               random_state=42, verbose=-1)
    tmp.fit(Xc_res, yc_res)
    cv_aucs.append(roc_auc_score(yc_val, tmp.predict_proba(Xc_val)[:, 1]))

cv_mean = np.mean(cv_aucs)
gap     = cv_mean - auc
print(f"   Proper CV AUC (SMOTE inside fold): {cv_mean:.4f}")
print(f"   Test AUC                         : {auc:.4f}")
print(f"   Gap                              : {gap:.4f}  {'✅ good' if gap < 0.04 else '⚠ still some overfit'}")

# ─────────────────────────────────────────────────────────────────────
# 14. PLOTS
# ─────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# ── ROC curve ────────────────────────────────────────────────────────
axes[0].plot(fpr, tpr, lw=2, color="steelblue", label=f"AUC = {auc:.4f}")
axes[0].plot([0, 1], [0, 1], "k--", lw=1)
thr_idx = np.argmin(np.abs(thresholds - best_thr))
axes[0].scatter(fpr[thr_idx], tpr[thr_idx], color="red", zorder=5,
                label=f"Chosen threshold = {best_thr:.2f}")
axes[0].set_xlabel("False Positive Rate"); axes[0].set_ylabel("True Positive Rate")
axes[0].set_title("ROC Curve"); axes[0].legend()

# ── Recall & Precision vs threshold ──────────────────────────────────
thrs    = np.arange(0.05, 0.60, 0.01)
recalls = [recall_score(y_test, (y_prob >= t).astype(int), zero_division=0) for t in thrs]
precs   = [precision_score(y_test, (y_prob >= t).astype(int), zero_division=0) for t in thrs]
axes[1].plot(thrs, recalls, color="coral",     lw=2, label="PCOS Recall")
axes[1].plot(thrs, precs,   color="steelblue", lw=2, label="PCOS Precision")
axes[1].axvline(best_thr, color="red", linestyle="--", label=f"Chosen = {best_thr:.2f}")
axes[1].axhline(TARGET_RECALL, color="gray", linestyle=":", alpha=0.6,
                label=f"Target recall {TARGET_RECALL}")
axes[1].set_xlabel("Threshold"); axes[1].set_ylabel("Score")
axes[1].set_title("Recall & Precision vs Threshold"); axes[1].legend(fontsize=8)

# ── Feature importance (LightGBM) ────────────────────────────────────
best_lgb_full = lgb.LGBMClassifier(**best_lgb_params, class_weight="balanced",
                                    random_state=42, verbose=-1)
best_lgb_full.fit(X_res, y_res)
fi = pd.Series(best_lgb_full.feature_importances_,
               index=X_tr_sel.columns).sort_values(ascending=False).head(15)
fi.plot(kind="barh", ax=axes[2], color="steelblue")
axes[2].invert_yaxis()
axes[2].set_title("Top 15 Features (LightGBM)")
axes[2].set_xlabel("Importance")

plt.tight_layout()
plt.savefig("/content/pcos_v5_results.png", dpi=150, bbox_inches="tight")
plt.show()
print("\n💾 Plot saved: /content/pcos_v5_results.png")

# ─────────────────────────────────────────────────────────────────────
# 15. SAVE MODEL BUNDLE TO GOOGLE DRIVE
# ─────────────────────────────────────────────────────────────────────
timestamp  = datetime.now().strftime("%Y%m%d_%H%M%S")
model_file = f"pcos_model_v5_{timestamp}.pkl"
local_path = f"/content/{model_file}"

bundle = {
    # Pipeline components (apply in this order for inference)
    "imputer"          : imputer,
    "scaler"           : scaler,
    "selector"         : selector,
    "model"            : calibrated,

    # Metadata
    "feature_columns"  : list(X_train.columns),    # raw sanitized features (pre-selection)
    "selected_features": selected_features,         # features after MI selection
    "col_name_map"     : col_map,                   # original → sanitized
    "optimal_threshold": float(best_thr),
    "test_auc"         : float(auc),
    "avg_precision"    : float(ap),
    "cv_auc"           : float(cv_mean),
    "overfit_gap"      : float(gap),
    "trained_at"       : timestamp,
}
joblib.dump(bundle, local_path)
print(f"\n💾 Model bundle saved: {local_path}")

try:
    from google.colab import drive
    drive.mount("/content/drive", force_remount=False)
    drive_dir = "/content/drive/MyDrive/PCOS_Model1"
    os.makedirs(drive_dir, exist_ok=True)
    shutil.copy(local_path, os.path.join(drive_dir, model_file))
    shutil.copy("/content/pcos_v5_results.png",
                os.path.join(drive_dir, f"pcos_v5_results_{timestamp}.png"))
    print(f"✅ Saved to Google Drive → MyDrive/PCOS_Model/")
    print(f"   📦 {model_file}")
    print(f"   📊 pcos_v5_results_{timestamp}.png")
except Exception as e:
    print(f"⚠️  Drive save failed: {e}")
    print(f"   Model still at: {local_path}")

# ─────────────────────────────────────────────────────────────────────
# 16. SUMMARY
# ─────────────────────────────────────────────────────────────────────
print(f"""
═══════════════════════════════════════════════════════════════
  SUMMARY
═══════════════════════════════════════════════════════════════
  Test AUC           : {auc:.4f}
  Avg Precision (AP) : {ap:.4f}
  CV AUC (proper)    : {cv_mean:.4f}
  Overfit gap        : {gap:.4f}  {'✅' if gap < 0.04 else '⚠'}
  Chosen threshold   : {best_thr:.2f}
  PCOS recall        : {recall_score(y_test, y_pred):.3f}
  PCOS precision     : {precision_score(y_test, y_pred):.3f}
  PCOS missed (FN)   : {fn}
═══════════════════════════════════════════════════════════════

  HOW TO USE THE SAVED MODEL FOR INFERENCE
═══════════════════════════════════════════════════════════════
import joblib, pandas as pd

b         = joblib.load("MyDrive/PCOS_Model/{model_file}")
features  = b["feature_columns"]   # sanitized names (pre-selection)
threshold = b["optimal_threshold"]

# new_df must have all columns in `features`
X_imp  = b["imputer"].transform(new_df[features])
X_sc   = b["scaler"].transform(X_imp)
X_sel  = b["selector"].transform(X_sc)
prob   = b["model"].predict_proba(X_sel)[:, 1][0]
pred   = "PCOS" if prob >= threshold else "No PCOS"
print(f"Probability: {{prob:.2%}}  →  {{pred}}")
═══════════════════════════════════════════════════════════════
""")

drive_path = "/content/drive/MyDrive/PCOS_Model2"
os.makedirs(drive_path, exist_ok=True)

model_path = os.path.join(drive_path, "/content/pcos_model_v7.pkl")

joblib.dump({
    "model": cal,
    "imputer": imp,
    "scaler": sc,
    "selector": sel,
    "threshold": best_thr,
    "feature_columns": list(X.columns)
}, model_path)

print(f"✅ Model saved to: {model_path}")

# ================================================================
# PCOS FINAL MODEL v7 (CLEAN + STABLE + HIGH RECALL)
# ================================================================

!pip install lightgbm optuna imbalanced-learn xgboost -q

import re, warnings, os, shutil
import numpy as np
import pandas as pd
import joblib

from datetime import datetime
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix, recall_score, precision_score
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.calibration import CalibratedClassifierCV
from imblearn.over_sampling import SMOTE

from xgboost import XGBClassifier
import lightgbm as lgb
import optuna

warnings.filterwarnings("ignore")

# ================================================================
# 1. LOAD & CLEAN
# ================================================================
df = pd.read_csv("/content/combined_pcos_data.csv")
df = df.drop(columns=["Sl. No", "Patient File No.", "Unnamed: 44"], errors="ignore")

def clean_numeric(x):
    if pd.isna(x): return np.nan
    m = re.search(r"\d+(\.\d+)?", str(x))
    return float(m.group()) if m else np.nan

for col in df.columns:
    df[col] = df[col].apply(clean_numeric)

# ================================================================
# 2. SANITIZE
# ================================================================
def sanitize(name):
    return re.sub(r"_+", "_", re.sub(r"[^\w]", "_", name)).strip("_")

df.columns = [sanitize(c) for c in df.columns]

def find_col(df, *keys):
    for col in df.columns:
        if all(k in col.lower() for k in keys):
            return col
    return None

TARGET = find_col(df, "pcos")

# ================================================================
# 3. FEATURE ENGINEERING (ROBUST)
# ================================================================
LH = find_col(df, "lh")
FSH = find_col(df, "fsh")
WT = find_col(df, "weight")
HT = find_col(df, "height")
CYCLE = find_col(df, "cycle")
FAST = find_col(df, "fast")

if WT and HT:
    df["BMI"] = df[WT] / ((df[HT]/100)**2)
else:
    df["BMI"] = 0

if LH and FSH:
    df["LH_FSH_ratio"] = df[LH] / (df[FSH] + 1e-5)
else:
    df["LH_FSH_ratio"] = 0

sym_cols = [c for c in df.columns if any(k in c.lower() for k in ["hair","pimples","skin","weight_gain"])]
df["symptom_score"] = df[sym_cols].fillna(0).sum(axis=1)

df["cycle_irregularity"] = (df[CYCLE] > 35).astype(int) if CYCLE else 0
df["metabolic_risk"] = df[FAST].fillna(0) if FAST else 0

# ================================================================
# 4. SPLIT
# ================================================================
X = df.drop(columns=[TARGET])
y = df[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# ================================================================
# 5. PREPROCESS
# ================================================================
imp = SimpleImputer(strategy="median")
sc = RobustScaler()

X_tr = sc.fit_transform(imp.fit_transform(X_train))
X_te = sc.transform(imp.transform(X_test))

# ================================================================
# 6. FEATURE SELECTION
# ================================================================
sel = SelectKBest(mutual_info_classif, k=30)
X_tr = sel.fit_transform(X_tr, y_train)
X_te = sel.transform(X_te)

# ================================================================
# 7. SMOTE
# ================================================================
sm = SMOTE(sampling_strategy=1.0, random_state=42)
X_res, y_res = sm.fit_resample(X_tr, y_train)

neg, pos = np.bincount(y_train.astype(int))
scale_pw = (neg / pos) * 1.5

# ================================================================
# 8. OPTUNA TUNING
# ================================================================
def xgb_obj(trial):
    m = XGBClassifier(
        n_estimators=300,
        max_depth=trial.suggest_int("max_depth", 3, 6),
        learning_rate=trial.suggest_float("lr", 0.01, 0.1),
        subsample=trial.suggest_float("sub", 0.6, 0.9),
        colsample_bytree=trial.suggest_float("cbt", 0.5, 0.9),
        scale_pos_weight=scale_pw,
        eval_metric="logloss"
    )
    return cross_val_score(m, X_res, y_res, cv=3, scoring="roc_auc").mean()

study = optuna.create_study(direction="maximize")
study.optimize(xgb_obj, n_trials=20)
params = study.best_params

# ================================================================
# 9. TRAIN MODELS (EARLY STOPPING)
# ================================================================
X_es_tr, X_es_val, y_es_tr, y_es_val = train_test_split(
    X_res, y_res, test_size=0.15, stratify=y_res, random_state=42
)

xgb = XGBClassifier(
    **params,
    n_estimators=1000,
    scale_pos_weight=scale_pw,
    eval_metric="logloss",
    early_stopping_rounds=30
)

xgb.fit(X_es_tr, y_es_tr, eval_set=[(X_es_val, y_es_val)], verbose=False)

lgbm = lgb.LGBMClassifier(
    n_estimators=1000,
    class_weight="balanced"
)

lgbm.fit(X_es_tr, y_es_tr,
         eval_set=[(X_es_val, y_es_val)],
         callbacks=[lgb.early_stopping(30, verbose=False)])

rf = RandomForestClassifier(n_estimators=300, class_weight="balanced")

# ================================================================
# 10. STACKING (FIXED)
# ================================================================
stack = StackingClassifier(
    estimators=[
        ("xgb", XGBClassifier(**params, n_estimators=xgb.best_iteration)),
        ("lgb", lgb.LGBMClassifier(n_estimators=lgbm.best_iteration_)),
        ("rf", rf)
    ],
    final_estimator=LogisticRegression(C=0.1, class_weight="balanced"),
    cv=5
)

stack.fit(X_res, y_res)

cal = CalibratedClassifierCV(stack, cv="prefit")
cal.fit(X_tr, y_train)

# ================================================================
# 11. EVALUATION (CONTROLLED RECALL)
# ================================================================
y_prob = cal.predict_proba(X_te)[:,1]

TARGET_RECALL = 0.88
MIN_PREC = 0.55
best_thr = 0.2

for t in np.arange(0.05, 0.5, 0.01):
    pred = (y_prob >= t).astype(int)
    rec = recall_score(y_test, pred)
    pre = precision_score(y_test, pred)
    if rec >= TARGET_RECALL and pre >= MIN_PREC:
        best_thr = t
        break

y_pred = (y_prob >= best_thr).astype(int)

print("\nFINAL RESULTS\n")
print("AUC:", roc_auc_score(y_test, y_prob))
print("Threshold:", best_thr)
print("\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# ================================================================
# 12. SAVE
# ================================================================
joblib.dump({
    "model": cal,
    "imputer": imp,
    "scaler": sc,
    "selector": sel,
    "threshold": best_thr
}, "/content/pcos_model_v7.pkl")

print("\nModel saved successfully!")

import os

drive_path = "/content/drive/MyDrive/tabPCOS_Model"
os.makedirs(drive_path, exist_ok=True)

import joblib
from datetime import datetime

# Create timestamp (recommended)
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

model_path = os.path.join(drive_path, f"pcos_model_v7_{timestamp}.pkl")

# Save full pipeline
joblib.dump({
    "model": cal,                 # calibrated stacking model
    "imputer": imp,
    "scaler": sc,
    "selector": sel,
    "threshold": best_thr,
    "feature_columns": list(X.columns)  # VERY IMPORTANT
}, model_path)

print(f"✅ Model saved to Drive: {model_path}")